const PROFISSIONAIS = [
  { nome: "Nádia",   funcao: "Cabeleireira" },
  { nome: "Simone",            funcao: "Cabeleireira" },
  { nome: "Alexandra",            funcao: "Designer" },
  { nome: "Samia",                   funcao: "Cabeleireira" },
  { nome: "Jéssica",           funcao: "Cabeleireira" },
  { nome: "Erica",       funcao: "Designer" },
  { nome: "Sandra",             funcao: "Cabeleireira" },
  { nome: "Mirla",                   funcao: "Cabeleireira" },
  { nome: "Ana Paula",           funcao: "Cabeleireira" },
  { nome: "Leila",    funcao: "Manicure" },
  { nome: "Yane",              funcao: "Manicure" },
  { nome: "Zilma",             funcao: "Manicure" },
  { nome: "Paula Gomes",                funcao: "Manicure" },
  { nome: "Leonara",    funcao: "Manicure" },
  { nome: "Claudia",               funcao: "Manicure" },
  { nome: "Sibelly",            funcao: "Manicure" },
  { nome: "Hilzilane",          funcao: "Manicure" },
  { nome: "Marilia",            funcao: "Manicure" },
  { nome: "Juliana Melo",           funcao: "Manicure" },
  { nome: "Nalva",  funcao: "Cabeleireira" },
  { nome: "Maria Rita",   funcao: "Manicure" },
  { nome: "Daniele",            funcao: "Manicure" },
  { nome: "Daiana",              funcao: "Manicure" },
  { nome: "Juliana Rodrigues",          funcao: "Manicure" },
  { nome: "Gabriela Johanna",          funcao: "Manicure" },
];